version: "3.9"

services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend-nava-ai
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-nava-ai:/app
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
